import type { ColorName } from '~/types/colorName'

import process from 'node:process'
import { config } from 'dotenv'
import { Dracula } from '~/enums/dracula'
import { DraculaPalettes } from '~/enums/draculaPalettes'

config({ path: '.env' })

// Dracula original
const dracula: Record<ColorName, string> = {
  rosewater: Dracula.PINK,
  flamingo: Dracula.PINK,
  pink: Dracula.PINK,
  mauve: Dracula.PURPLE,
  red: Dracula.RED,
  maroon: Dracula.RED,
  peach: Dracula.ORANGE,
  yellow: Dracula.YELLOW,
  green: Dracula.GREEN,
  teal: Dracula.CYAN,
  sky: Dracula.CYAN,
  sapphire: Dracula.CYAN,
  blue: Dracula.CYAN,
  lavender: Dracula.CYAN,
  text: Dracula.FOREGROUND,
  subtext1: Dracula.FOREGROUND,
  subtext0: Dracula.FOREGROUND,
  overlay2: Dracula.COMMENT,
  overlay1: Dracula.COMMENT,
  overlay0: Dracula.COMMENT,
  surface2: Dracula.SELECTION,
  surface1: Dracula.SELECTION,
  surface0: Dracula.SELECTION,
  base: Dracula.BACKGROUND,
  mantle: Dracula.BACKGROUND,
  crust: Dracula.BACKGROUND,
}

// Dracula Pro
const draculaPro: Record<ColorName, string> = {
  rosewater: process.env.PRO_PINK ?? Dracula.PINK,
  flamingo: process.env.PRO_PINK ?? Dracula.PINK,
  pink: process.env.PRO_PINK ?? Dracula.PINK,
  mauve: process.env.PRO_PURPLE ?? Dracula.PURPLE,
  red: process.env.PRO_RED ?? Dracula.RED,
  maroon: process.env.PRO_RED ?? Dracula.RED,
  peach: process.env.PRO_ORANGE ?? Dracula.ORANGE,
  yellow: process.env.PRO_YELLOW ?? Dracula.YELLOW,
  green: process.env.PRO_GREEN ?? Dracula.GREEN,
  teal: process.env.PRO_CYAN ?? Dracula.CYAN,
  sky: process.env.PRO_CYAN ?? Dracula.CYAN,
  sapphire: process.env.PRO_CYAN ?? Dracula.CYAN,
  blue: process.env.PRO_CYAN ?? Dracula.CYAN,
  lavender: process.env.PRO_CYAN ?? Dracula.CYAN,
  text: process.env.PRO_FOREGROUND ?? Dracula.FOREGROUND,
  subtext1: process.env.PRO_FOREGROUND ?? Dracula.FOREGROUND,
  subtext0: process.env.PRO_FOREGROUND ?? Dracula.FOREGROUND,
  overlay2: process.env.PRO_COMMENT ?? Dracula.COMMENT,
  overlay1: process.env.PRO_COMMENT ?? Dracula.COMMENT,
  overlay0: process.env.PRO_COMMENT ?? Dracula.COMMENT,
  surface2: process.env.PRO_SELECTION ?? Dracula.SELECTION,
  surface1: process.env.PRO_SELECTION ?? Dracula.SELECTION,
  surface0: process.env.PRO_SELECTION ?? Dracula.SELECTION,
  base: process.env.PRO_BACKGROUND ?? Dracula.BACKGROUND,
  mantle: process.env.PRO_BACKGROUND ?? Dracula.BACKGROUND,
  crust: process.env.PRO_BACKGROUND ?? Dracula.BACKGROUND,
}

// Dracula Pro Blade
const draculaProBlade: Record<ColorName, string> = {
  rosewater: process.env.PRO_PINK ?? Dracula.PINK,
  flamingo: process.env.PRO_PINK ?? Dracula.PINK,
  pink: process.env.PRO_PINK ?? Dracula.PINK,
  mauve: process.env.PRO_PURPLE ?? Dracula.PURPLE,
  red: process.env.PRO_RED ?? Dracula.RED,
  maroon: process.env.PRO_RED ?? Dracula.RED,
  peach: process.env.PRO_ORANGE ?? Dracula.ORANGE,
  yellow: process.env.PRO_YELLOW ?? Dracula.YELLOW,
  green: process.env.PRO_GREEN ?? Dracula.GREEN,
  teal: process.env.PRO_CYAN ?? Dracula.CYAN,
  sky: process.env.PRO_CYAN ?? Dracula.CYAN,
  sapphire: process.env.PRO_CYAN ?? Dracula.CYAN,
  blue: process.env.PRO_CYAN ?? Dracula.CYAN,
  lavender: process.env.PRO_CYAN ?? Dracula.CYAN,
  text: process.env.PRO_FOREGROUND ?? Dracula.FOREGROUND,
  subtext1: process.env.PRO_FOREGROUND ?? Dracula.FOREGROUND,
  subtext0: process.env.PRO_FOREGROUND ?? Dracula.FOREGROUND,
  overlay2: process.env.BLADE_COMMENT ?? Dracula.COMMENT,
  overlay1: process.env.BLADE_COMMENT ?? Dracula.COMMENT,
  overlay0: process.env.BLADE_COMMENT ?? Dracula.COMMENT,
  surface2: process.env.BLADE_SELECTION ?? Dracula.SELECTION,
  surface1: process.env.BLADE_SELECTION ?? Dracula.SELECTION,
  surface0: process.env.BLADE_SELECTION ?? Dracula.SELECTION,
  base: process.env.BLADE_BACKGROUND ?? Dracula.BACKGROUND,
  mantle: process.env.BLADE_BACKGROUND ?? Dracula.BACKGROUND,
  crust: process.env.BLADE_BACKGROUND ?? Dracula.BACKGROUND,
}

// Dracula Pro Buffy
const draculaProBuffy: Record<ColorName, string> = {
  rosewater: process.env.PRO_PINK ?? Dracula.PINK,
  flamingo: process.env.PRO_PINK ?? Dracula.PINK,
  pink: process.env.PRO_PINK ?? Dracula.PINK,
  mauve: process.env.PRO_PURPLE ?? Dracula.PURPLE,
  red: process.env.PRO_RED ?? Dracula.RED,
  maroon: process.env.PRO_RED ?? Dracula.RED,
  peach: process.env.PRO_ORANGE ?? Dracula.ORANGE,
  yellow: process.env.PRO_YELLOW ?? Dracula.YELLOW,
  green: process.env.PRO_GREEN ?? Dracula.GREEN,
  teal: process.env.PRO_CYAN ?? Dracula.CYAN,
  sky: process.env.PRO_CYAN ?? Dracula.CYAN,
  sapphire: process.env.PRO_CYAN ?? Dracula.CYAN,
  blue: process.env.PRO_CYAN ?? Dracula.CYAN,
  lavender: process.env.PRO_CYAN ?? Dracula.CYAN,
  text: process.env.PRO_FOREGROUND ?? Dracula.FOREGROUND,
  subtext1: process.env.PRO_FOREGROUND ?? Dracula.FOREGROUND,
  subtext0: process.env.PRO_FOREGROUND ?? Dracula.FOREGROUND,
  overlay2: process.env.BUFFY_COMMENT ?? Dracula.COMMENT,
  overlay1: process.env.BUFFY_COMMENT ?? Dracula.COMMENT,
  overlay0: process.env.BUFFY_COMMENT ?? Dracula.COMMENT,
  surface2: process.env.BUFFY_SELECTION ?? Dracula.SELECTION,
  surface1: process.env.BUFFY_SELECTION ?? Dracula.SELECTION,
  surface0: process.env.BUFFY_SELECTION ?? Dracula.SELECTION,
  base: process.env.BUFFY_BACKGROUND ?? Dracula.BACKGROUND,
  mantle: process.env.BUFFY_BACKGROUND ?? Dracula.BACKGROUND,
  crust: process.env.BUFFY_BACKGROUND ?? Dracula.BACKGROUND,
}

// Dracula Pro Lincoln
const draculaProLincoln: Record<ColorName, string> = {
  rosewater: process.env.PRO_PINK ?? Dracula.PINK,
  flamingo: process.env.PRO_PINK ?? Dracula.PINK,
  pink: process.env.PRO_PINK ?? Dracula.PINK,
  mauve: process.env.PRO_PURPLE ?? Dracula.PURPLE,
  red: process.env.PRO_RED ?? Dracula.RED,
  maroon: process.env.PRO_RED ?? Dracula.RED,
  peach: process.env.PRO_ORANGE ?? Dracula.ORANGE,
  yellow: process.env.PRO_YELLOW ?? Dracula.YELLOW,
  green: process.env.PRO_GREEN ?? Dracula.GREEN,
  teal: process.env.PRO_CYAN ?? Dracula.CYAN,
  sky: process.env.PRO_CYAN ?? Dracula.CYAN,
  sapphire: process.env.PRO_CYAN ?? Dracula.CYAN,
  blue: process.env.PRO_CYAN ?? Dracula.CYAN,
  lavender: process.env.PRO_CYAN ?? Dracula.CYAN,
  text: process.env.PRO_FOREGROUND ?? Dracula.FOREGROUND,
  subtext1: process.env.PRO_FOREGROUND ?? Dracula.FOREGROUND,
  subtext0: process.env.PRO_FOREGROUND ?? Dracula.FOREGROUND,
  overlay2: process.env.LINCOLN_COMMENT ?? Dracula.COMMENT,
  overlay1: process.env.LINCOLN_COMMENT ?? Dracula.COMMENT,
  overlay0: process.env.LINCOLN_COMMENT ?? Dracula.COMMENT,
  surface2: process.env.LINCOLN_SELECTION ?? Dracula.SELECTION,
  surface1: process.env.LINCOLN_SELECTION ?? Dracula.SELECTION,
  surface0: process.env.LINCOLN_SELECTION ?? Dracula.SELECTION,
  base: process.env.LINCOLN_BACKGROUND ?? Dracula.BACKGROUND,
  mantle: process.env.LINCOLN_BACKGROUND ?? Dracula.BACKGROUND,
  crust: process.env.LINCOLN_BACKGROUND ?? Dracula.BACKGROUND,
}

// Dracula Pro Morbius
const draculaProMorbius: Record<ColorName, string> = {
  rosewater: process.env.PRO_PINK ?? Dracula.PINK,
  flamingo: process.env.PRO_PINK ?? Dracula.PINK,
  pink: process.env.PRO_PINK ?? Dracula.PINK,
  mauve: process.env.PRO_PURPLE ?? Dracula.PURPLE,
  red: process.env.PRO_RED ?? Dracula.RED,
  maroon: process.env.PRO_RED ?? Dracula.RED,
  peach: process.env.PRO_ORANGE ?? Dracula.ORANGE,
  yellow: process.env.PRO_YELLOW ?? Dracula.YELLOW,
  green: process.env.PRO_GREEN ?? Dracula.GREEN,
  teal: process.env.PRO_CYAN ?? Dracula.CYAN,
  sky: process.env.PRO_CYAN ?? Dracula.CYAN,
  sapphire: process.env.PRO_CYAN ?? Dracula.CYAN,
  blue: process.env.PRO_CYAN ?? Dracula.CYAN,
  lavender: process.env.PRO_CYAN ?? Dracula.CYAN,
  text: process.env.PRO_FOREGROUND ?? Dracula.FOREGROUND,
  subtext1: process.env.PRO_FOREGROUND ?? Dracula.FOREGROUND,
  subtext0: process.env.PRO_FOREGROUND ?? Dracula.FOREGROUND,
  overlay2: process.env.MORBIUS_COMMENT ?? Dracula.COMMENT,
  overlay1: process.env.MORBIUS_COMMENT ?? Dracula.COMMENT,
  overlay0: process.env.MORBIUS_COMMENT ?? Dracula.COMMENT,
  surface2: process.env.MORBIUS_SELECTION ?? Dracula.SELECTION,
  surface1: process.env.MORBIUS_SELECTION ?? Dracula.SELECTION,
  surface0: process.env.MORBIUS_SELECTION ?? Dracula.SELECTION,
  base: process.env.MORBIUS_BACKGROUND ?? Dracula.BACKGROUND,
  mantle: process.env.MORBIUS_BACKGROUND ?? Dracula.BACKGROUND,
  crust: process.env.MORBIUS_BACKGROUND ?? Dracula.BACKGROUND,
}

// Dracula Pro Van Helsing
const draculaProVanHelsing: Record<ColorName, string> = {
  rosewater: process.env.PRO_PINK ?? Dracula.PINK,
  flamingo: process.env.PRO_PINK ?? Dracula.PINK,
  pink: process.env.PRO_PINK ?? Dracula.PINK,
  mauve: process.env.PRO_PURPLE ?? Dracula.PURPLE,
  red: process.env.PRO_RED ?? Dracula.RED,
  maroon: process.env.PRO_RED ?? Dracula.RED,
  peach: process.env.PRO_ORANGE ?? Dracula.ORANGE,
  yellow: process.env.PRO_YELLOW ?? Dracula.YELLOW,
  green: process.env.PRO_GREEN ?? Dracula.GREEN,
  teal: process.env.PRO_CYAN ?? Dracula.CYAN,
  sky: process.env.PRO_CYAN ?? Dracula.CYAN,
  sapphire: process.env.PRO_CYAN ?? Dracula.CYAN,
  blue: process.env.PRO_CYAN ?? Dracula.CYAN,
  lavender: process.env.PRO_CYAN ?? Dracula.CYAN,
  text: process.env.PRO_FOREGROUND ?? Dracula.FOREGROUND,
  subtext1: process.env.PRO_FOREGROUND ?? Dracula.FOREGROUND,
  subtext0: process.env.PRO_FOREGROUND ?? Dracula.FOREGROUND,
  overlay2: process.env.VAN_HELSING_COMMENT ?? Dracula.COMMENT,
  overlay1: process.env.VAN_HELSING_COMMENT ?? Dracula.COMMENT,
  overlay0: process.env.VAN_HELSING_COMMENT ?? Dracula.COMMENT,
  surface2: process.env.VAN_HELSING_SELECTION ?? Dracula.SELECTION,
  surface1: process.env.VAN_HELSING_SELECTION ?? Dracula.SELECTION,
  surface0: process.env.VAN_HELSING_SELECTION ?? Dracula.SELECTION,
  base: process.env.VAN_HELSING_BACKGROUND ?? Dracula.BACKGROUND,
  mantle: process.env.VAN_HELSING_BACKGROUND ?? Dracula.BACKGROUND,
  crust: process.env.VAN_HELSING_BACKGROUND ?? Dracula.BACKGROUND,
}

// Dracula Pro Alucard
const draculaProAlucard: Record<ColorName, string> = {
  rosewater: process.env.ALUCARD_PINK ?? Dracula.PINK,
  flamingo: process.env.ALUCARD_PINK ?? Dracula.PINK,
  pink: process.env.ALUCARD_PINK ?? Dracula.PINK,
  mauve: process.env.ALUCARD_PURPLE ?? Dracula.PURPLE,
  red: process.env.ALUCARD_RED ?? Dracula.RED,
  maroon: process.env.ALUCARD_RED ?? Dracula.RED,
  peach: process.env.ALUCARD_ORANGE ?? Dracula.ORANGE,
  yellow: process.env.ALUCARD_YELLOW ?? Dracula.YELLOW,
  green: process.env.ALUCARD_GREEN ?? Dracula.GREEN,
  teal: process.env.ALUCARD_CYAN ?? Dracula.CYAN,
  sky: process.env.ALUCARD_CYAN ?? Dracula.CYAN,
  sapphire: process.env.ALUCARD_CYAN ?? Dracula.CYAN,
  blue: process.env.ALUCARD_CYAN ?? Dracula.CYAN,
  lavender: process.env.ALUCARD_CYAN ?? Dracula.CYAN,
  text: process.env.ALUCARD_FOREGROUND ?? Dracula.FOREGROUND,
  subtext1: process.env.ALUCARD_FOREGROUND ?? Dracula.FOREGROUND,
  subtext0: process.env.ALUCARD_FOREGROUND ?? Dracula.FOREGROUND,
  overlay2: process.env.ALUCARD_COMMENT ?? Dracula.COMMENT,
  overlay1: process.env.ALUCARD_COMMENT ?? Dracula.COMMENT,
  overlay0: process.env.ALUCARD_COMMENT ?? Dracula.COMMENT,
  surface2: process.env.ALUCARD_SELECTION ?? Dracula.SELECTION,
  surface1: process.env.ALUCARD_SELECTION ?? Dracula.SELECTION,
  surface0: process.env.ALUCARD_SELECTION ?? Dracula.SELECTION,
  base: process.env.ALUCARD_BACKGROUND ?? Dracula.BACKGROUND,
  mantle: process.env.ALUCARD_BACKGROUND ?? Dracula.BACKGROUND,
  crust: process.env.ALUCARD_BACKGROUND ?? Dracula.BACKGROUND,
}

/**
 * Simplified ColorName/Hexcode palettes
 */
export const palettes = {
  [DraculaPalettes.VARIABLES]: Object.entries(dracula).map(([color]) => [
    color,
    `var(--vscode-ctp-${color})`,
  ]) as Array<[ColorName, string]>,
  [DraculaPalettes.Dracula]: Object.entries(dracula) as Array<[ColorName, string]>,
  [DraculaPalettes.DraculaPro]: Object.entries(draculaPro) as Array<[ColorName, string]>,
  [DraculaPalettes.DraculaProBlade]: Object.entries(draculaProBlade) as Array<[ColorName, string]>,
  [DraculaPalettes.DraculaProBuffy]: Object.entries(draculaProBuffy) as Array<[ColorName, string]>,
  [DraculaPalettes.DraculaProLincoln]: Object.entries(draculaProLincoln) as Array<[ColorName, string]>,
  [DraculaPalettes.DraculaProMorbius]: Object.entries(draculaProMorbius) as Array<[ColorName, string]>,
  [DraculaPalettes.DraculaProVanHelsing]: Object.entries(draculaProVanHelsing) as Array<[ColorName, string]>,
  [DraculaPalettes.DraculaProAlucard]: Object.entries(draculaProAlucard) as Array<[ColorName, string]>,
}

export const folders = [
  DraculaPalettes.VARIABLES,
  DraculaPalettes.Dracula,
  DraculaPalettes.DraculaPro,
  DraculaPalettes.DraculaProBlade,
  DraculaPalettes.DraculaProBuffy,
  DraculaPalettes.DraculaProLincoln,
  DraculaPalettes.DraculaProMorbius,
  DraculaPalettes.DraculaProVanHelsing,
  DraculaPalettes.DraculaProAlucard,
] satisfies Array<DraculaPalettes>
